[package]
name = "scrobble-tool"
version = "0.1.0"
authors = ["David Futcher <david.futcher@skyscanner.net>"]

[dependencies]
bitflags = "1.0"
discogs = "0.2.1"
env_logger = "0.4.3"
getopts = "0.2"
log = "0.3"
rustfm-scrobble = "0.9.1"
